### ISSUE TITLE
H1 H3 cannot match the corresponding pads on the PCB board

### ISSUE THREAD

**Issue by flexmatics** [nliaudat/esp32_8ch_motor_shield#11]
Hey,

Ordered PCB using the files here: https://github.com/nliaudat/esp32_8ch_motor_shield/releases/tag/v54

JCB gave this reply:
![image](https://user-images.githubusercontent.com/79056776/184002748-04b83473-3d8f-4eaf-9bf7-f5cba6864396.png)

Deselected these parts as didn't know what to do - did I mess up or can still expect to get working board?
Corrected PDF from JCB should look like this: 
![image](https://user-images.githubusercontent.com/79056776/184003086-5f6229cc-3d52-4002-9ca2-2bf96d605b0e.png)

Thanks.

**Comment by nliaudat** [comment]
Hi, 
H1 and H3 are only mounting holes. You can delete them safely. 
I've ordered many time that PCB and they never complain ...
H1 and H3 have enough space in easyeda.
Regards
