### ISSUE TITLE
Not an issue: I will have 6 assembled boards available for german buyers...

### ISSUE THREAD

**Issue by Lonestar78** [nliaudat/esp32_8ch_motor_shield#12]
Dear All,

not exactly an issue ;-)
i just ordered 10 assembled PCBs and can make 6 available for buyers (cheapest shipping in Germany)
Let me know if interessted.

Kind regards
Christian

**Comment by ChristianBuer** [comment]
Hi,
I am interested. How much would three of them cost with shipping in Germany (I live in Wuppertal).

Kind regards,
Christian

**Comment by Lonestar78** [comment]
Hi, I would say about 22 € per assembled PCB plus DHL. The delivery should be at my door next week.
Kind regards Christian


Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by linuxdep** [comment]
Hi, schön, ich hätte auch Interesse an 2 PCB's. Ist der ESP32 auch dabei?

**Comment by Lonestar78** [comment]
Hi, would be without the ESP32, but i need to check how many i ordered on ali ;-)
If both above tke the PCBs i would have 2 more to offer.
which forum are you in? I can generate an account there.

**Comment by linuxdep** [comment]
https://homematic-forum.de/forum/
Da passt es ja hin...

**Comment by Lonestar78** [comment]
done... same username as on git

**Comment by danif86** [comment]
I need 3, only 1 left? And live in Norway (would pay for shipping)

**Comment by nliaudat** [comment]
Hi, I've created a discussion to buy or sell boards : 
https://github.com/nliaudat/esp32_8ch_motor_shield/discussions/categories/buy-or-sell

**Comment by playya** [comment]
@Lonestar78 I need only a single board and as a software guy to dump to order at JLCPCB.
Is the last board still available?
