### ISSUE TITLE
SCREW_HOLE_GROUD  

### ISSUE THREAD

**Issue by WMP** [nliaudat/esp32_8ch_motor_shield#23]
Hell, i want  to order this PCB on JLCPCB, but there isnt SCREW_HOLE_GROU available. 

![Screenshot_20221005_141901](https://user-images.githubusercontent.com/45381/194058705-49e2eb65-573b-414b-99ba-77686245b54b.png)

Do you know how to found this part in JLCPCB?

**Comment by nliaudat** [comment]
Hi, this is not a part. That's screw holes. I mean you can ignore it

**Comment by WMP** [comment]
Thank you, that's what I thought but I preferred to make sure.
