### ISSUE TITLE
[FEATURE REQUEST] Create new board to connect DHTxx or DS18B20 thermometers.

### ISSUE THREAD

**Issue by WMP** [nliaudat/esp32_8ch_motor_shield#24]
**Describe the problem you have/What new integration you would like**
I have a house in which each room has two RJ45 jacks in the wall. In one socket I always have a DS18B20 or DHT11/22 temperature sensor, and the other is a regular Ethernet. Currently, I have spaghetti-style cables connected in the patchpanel and connected to the esp8266 wroom. This is extremely ugly and hard to maintain and service. I wanted to create a board in easyPSB that would end the mess, but I have absolutely no knowledge of the subject, and this would be my first board. That's why I thought you might want to implement my idea. 

**Please describe your use case for this integration and alternatives you've tried:**
The board should have space for esp32/esp8266 wroom, a USB socket for power, and be surrounded by RJ45 sockets.  Each socket should be labeled with which GPIO port it is plugged into.  

There should be two jumpers at each socket: 
One should select whether a One-Wire or DHTxx sensor is plugged into the port. If the jumper is set to One-Wire mode, then one of the wires of the RJ45 connector should be connected to the GPIO port of your choice on the ESP wroom. Of course, all RJ45 jacks set to One-Wire should be connected to the same GPIO port, and there should be a 4.7kOHM resistor between the "One-Wire bus" and the GPIO port. 

Setting to DHTxx mode should connect one wire to a separate GPIO port. DHT requires a 10kOhm resistor, but because of the distance, a different resistor may work better. I don't know if it is a good idea to install a 10kOhm resistor for each socket. or are there adjustable resistors? Each socket should have a separate GPIO port.

However, there are cases when there are too many DS18B20s plugged into one GPIO port. I think then you can set a jumper to DHTxx mode and have a separate One-Wire bus to such a port. 

The other jumper should set a voltage of 3.3V or, for a longer distance 5V. Since the ESP does not have a 5V power supply, you would have to take it directly from the USB socket. 

**Additional context**

Multiple DHTxx wiring: 
![image](https://user-images.githubusercontent.com/45381/194616485-071b6632-fb63-437e-855e-fcbfe5f554b6.png)
Multiple DS18B20 wiring: 
![image](https://user-images.githubusercontent.com/45381/194617085-73f771de-e2b2-48c9-bd0f-08030a787fb1.png)

**Comment by nliaudat** [comment]
The actual board is a dev board with many free gpio available for [extensions](https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/extension.md).

You could modify as you want, add more sensors with the free gpios. If you need RJ45 socket and custom integration without the knowledge to add it yourself, you are in the wrong place.

Regards
