### ISSUE TITLE
[BUG] CH6 input shorted to CH7/8 BEMF

### ISSUE THREAD

**Issue by microtronics** [nliaudat/esp32_8ch_motor_shield#27]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

V54r1.35 Board

**Description of problem:**
The via shorts CH6 input to CH7/8 bemf
Didn't the DRC show this error?
![CH6short](https://user-images.githubusercontent.com/6690168/201043605-a158eec6-0a41-4a06-ab4b-fac631926406.png)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by nliaudat** [comment]
Many thanks, fix is done.
