### ISSUE TITLE
EasyEDA Project source

### ISSUE THREAD

**Issue by rubenmuehlhans** [nliaudat/esp32_8ch_motor_shield#3]
Awesome work! Thank you!
I need to drive 10 Homematic valve actuators. Would you like to share your easyeda project source, so that i can update the pcb layout?

**Comment by nliaudat** [comment]
I do not share the PCB source cause I'll will commercialize soon. 
For 5.8$, you can got a second PCB card and use it as an extension board or a standalone (recommended)

**Comment by nstadigs** [comment]
> I'll will commercialize soon

Great to hear! If the price is right I'll buy two of them :)
