### ISSUE TITLE
Documentation: Add dimensions of the board and the box

### ISSUE THREAD

**Issue by heinemannj** [nliaudat/esp32_8ch_motor_shield#43]
Please add the dimensions of the board and the box in documentation.

The dimensions within
https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/pcb/Schematic_esp32-8ch-dc-motor-shield_AC_2023-03-18.pdf
confusing me.

Cheers
Joerg

**Comment by nliaudat** [comment]
Fixed : https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/pcb/PCB_PCB%20v58%20rev%201.51_2023-10-02.pdf
