### ISSUE TITLE
Documentation: Difference between Floor heating and Motor control firmware

### ISSUE THREAD

**Issue by heinemannj** [nliaudat/esp32_8ch_motor_shield#44]
Please clarify about the differences, the approach and possible use cases for:

**Floor heating** : https://github.com/nliaudat/floor-heating-controller
**Motor control** : https://github.com/nliaudat/esphome-8-ch-motor-controller

Cheers
Joerg

**Comment by nliaudat** [comment]
1) Floor heating use the climate components to control motor

2) Motor version is to control any kind of motors, like steppers. You can use the esphome hbridge component.
