### ISSUE TITLE
Documentation: Usage of 1-wire temperature sensors

### ISSUE THREAD

**Issue by heinemannj** [nliaudat/esp32_8ch_motor_shield#45]
Usage of 1-wire temperature sensors (DS18B20):
https://esphome.io/components/sensor/dallas.html

_"... The 1-Wire bus ... should have an external pullup resistor of about 4.7KΩ. ..."
"... For this, connect a resistor of about 4.7KΩ between 3.3V and the data pin. ..."
"... Values ± 1KΩ will, in most cases, work fine as well, if you don’t have massively long wires. ..."_

|1-Wire Bus|Board|DS18B20|Resistor|
|---|------|-------|--|
|Power|VCC (3.3. V)|red|~4.7KΩ between Power and Data|
|Ground|GND|black|-|
|Data|IO (e.g. IO22)|yellow|~4.7KΩ between Power and Data|

See:
https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/extension.md

Note:
With proper and short cabling more than 16 DS18B20 on the same 1-wire bus seems to be possible.

**Comment by nliaudat** [comment]
Fix in https://github.com/nliaudat/esp32_8ch_motor_shield/wiki/1%E2%80%90wire-temperature-sensors
