### ISSUE TITLE
Move the rj11 connectors a little bit over the edge of the board

### ISSUE THREAD

**Issue by nstadigs** [nliaudat/esp32_8ch_motor_shield#5]
It would be great if the connectors stuck out from the board by a couple of millimeters.

**Please describe your use case for this integration and alternatives you've tried:**

I wanted to create a custom 3d printed box for my two boards with individual holes for the separate rj11 connectors, but it's hard to do when they are aligned with the edge of the board.

**Additional context**

**Comment by nliaudat** [comment]
![board_cut](https://user-images.githubusercontent.com/6782613/142875431-bd90fdd1-ad5d-44d6-8421-5abafe9f13e9.png)

There is a track for connecting motors without an RJ45 connector which is at the edge of the board and which locks the location of the RJ45 connector. I'll do some tests to move it, but in the meantime the easiest way is to cut the board.

**Comment by nstadigs** [comment]
Oh, that's great to hear! Then I'll just cut it :)

Thanks!

**Comment by nliaudat** [comment]
done in v53 release
