### ISSUE TITLE
Need help - Order Error jlcpcb.com

### ISSUE THREAD

**Issue by grericht** [nliaudat/esp32_8ch_motor_shield#50]
Get this Error ordering by jlcpcb.com

The below parts won't be assembled due to data missing.
WROOM-LEFT1,WROOM-RIGHT,WROOM-LEFT,HLK-PM03,P1,P2,P3,P4,H4,H5,OPAMP-H1,U1 designators don't exist in the BOM file.

![Screenshot 2024-02-20 114108](https://github.com/nliaudat/esp32_8ch_motor_shield/assets/128326089/2a60a737-b8dc-4230-9047-2248655f93b5)

**Comment by nliaudat** [comment]
For P5 to P12 +  Screw-230V, select part #C8465
H1, H3 are holes, the is no part

**Comment by nliaudat** [comment]
[BOM_esp32-8ch-dc-motor-shield_AC_2024-02-20.csv](https://github.com/nliaudat/esp32_8ch_motor_shield/files/14349458/BOM_esp32-8ch-dc-motor-shield_AC_2024-02-20.csv)
New BOM file

**Comment by nliaudat** [comment]
https://github.com/nliaudat/esp32_8ch_motor_shield/releases/tag/v58_rev_1.52

**Comment by grericht** [comment]
new bom file still not working. but using part #C8465 helps!
