### ISSUE TITLE
[BUG] - short circuit at BMEF in Bord: v57 rev 1.48

### ISSUE THREAD

**Issue by DerMo92** [nliaudat/esp32_8ch_motor_shield#55]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

**ESP (ESP32/ESP8266, Board/Sonoff):**

**ESPHome version (latest production, beta, dev branch)**

**Affected component:**

**Description of problem:**

Bord: v57 rev 1.48 
At latest version of this Board with RJ10. I wanted to use this version since I'm using the original Motors with RJ10 Plug. 
while using it the BMEF ( Mesures of the Channels to see if end stops
are reached) I always got 0,008V. That is basically short circuit. After a long investigation with a friend we found out, that all four channels have a short circuit to ground at the pin holes though the board. Compared to the latest version they are not isolated at the bottom layer to the Ground Polygone. (check images below) 
I suggest a warning in the Documentation for now and at best a correction in the Gerberfile. For me it was too late - we repaired it manually - for anyone who has the same issue check below.

![image](https://github.com/nliaudat/esp32_8ch_motor_shield/assets/98593122/134b64cd-c61a-4217-9680-b9a8c1e9369d)

![image](https://github.com/nliaudat/esp32_8ch_motor_shield/assets/98593122/f9dd0f32-5334-402a-a4ee-ea8517ef4ec9)

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by nliaudat** [comment]
Many thanks for showing that issue. 
I've corrected the release https://github.com/nliaudat/esp32_8ch_motor_shield/releases/tag/v57

It's too late, but I recommend you to use only the latest versions, even if the connectors no longer use RJ11. 
Just cut your cables and follow https://github.com/nliaudat/esp32_8ch_motor_shield/blob/main/VDMOT_wiring.md. 

Thanks again for this bug report.
