### ISSUE TITLE
5V power supply of ESP32

### ISSUE THREAD

**Issue by THorst92** [nliaudat/esp32_8ch_motor_shield#73]
Hi, I have one question:
As far as I understand the board, the ESP32 is powered by defaut with 3.3V.
Do I have to remove the diode connection between the ESP32 and 5V then? Or is this part not included in the BOM?
![image](https://github.com/user-attachments/assets/a3e39aed-479e-4c45-9f8f-e8cf99a8885d)

**Comment by nliaudat** [comment]
Hi, 
The esp32 board is powered with 5V ( 5-12V) as esp32 has is own voltage regulator. 
The diode is here to not discarge esp32 dedicaded capacitors. 
Do not remove the diode.

**Comment by nliaudat** [comment]
https://github.com/nliaudat/esp32_8ch_motor_shield/wiki/Project-rules
