### ISSUE TITLE
In the latest version + and - are connected

### ISSUE THREAD

**Issue by nstadigs** [nliaudat/esp32_8ch_motor_shield#8]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

N/A

**ESP (ESP32/ESP8266, Board/Sonoff):**

N/A

**ESPHome version (latest production, beta, dev branch)**

N/A
**Affected component:**

N/A

**Description of problem:**
In the latest version 3.3v and ground are connected

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

It's probably this, right?

![image](https://user-images.githubusercontent.com/588215/146267359-8d04f9d7-306e-4f60-8bec-368a55a6a4b3.png)

**Comment by nliaudat** [comment]
I see. 
Can you send the part number of the HLK 3.3V power supply.

**Comment by nstadigs** [comment]
It's the HLK-5M03 provided in the BOM file: C209906

**Comment by nstadigs** [comment]
To clarify, they are connected even on a bare board with nothing soldered

**Comment by nstadigs** [comment]
I should be able to just drill out these VCC holes to see if that fixes the problem, right? If so, I can just connect the 3.3v elsewhere with a cable. What do you think?

**Comment by nstadigs** [comment]
I can confirm that this solved the issue
![P_20211216_101123_1](https://user-images.githubusercontent.com/588215/146342643-7c1b1d75-8cb8-4899-a72b-41104ed4a811.jpg)

**Comment by nliaudat** [comment]
Sorry for that issue. The HLK footprints were wrong. I'll add extra space in next release

**Comment by nliaudat** [comment]
Fixed in release V54
